feat(pages): add pages on environments, testing, the tech test
TheDataShed/EngineeringHandbook pull request #92
Opened 2023-03-15 08:49 UTC by KingMichaelPark

2023-03-15 09:07 UTC, GooseLF requested changes
Sorry for being picky 🥸

2023-03-15 09:07 UTC, GooseLF commented on guides/testing.md
> +maintainers to understand expected behaviour
Full stop missing after "behaviour"

2023-03-15 09:07 UTC, GooseLF commented on guides/interview/preparatory-explanation.md
> +obviously get more challenging as they go along.
Not to be _that guy_ but, is it obvious? I think maybe this reads better as:

```
There are 5 more questions beyond this one with the questions becoming more challenging as you progress through the test.
```

Or something like that?

Also, are there 5 more questions beyond this? I thought there were 5 questions total, which would make it 4 questions beyond this? :p

2023-03-15 15:12 UTC, KingMichaelPark commented on guides/environments.md
> +that the code running pertains to the correct environment that it is suited for.
It's on line 20?

2023-03-15 15:14 UTC, GooseLF commented on guides/environments.md
> +that the code running pertains to the correct environment that it is suited for.
HurrDurr. Was too early 😂

2023-05-15 08:29 UTC, GooseLF approved these changes

2025-07-21 07:45 UTC, closed without merging